studies:
    letter_spacing:
        dir: letter_spacing_study
        groups:
            1: control
        subjects:
            control: [baan, baga, buzs, csen, cszs, daal, egfe, fada,
                        fipa, glad, kafe, kami, koma, kosz, krri, kukr,
                        naab, naev, nape, nesz, pavi, peju, vazo, zoad]
        experiments:
            et:
                features_path: '/data/letter_spacing_study/ET_features/24subjects_0s_0s.xls'
                conditions: [MS, NS, DS]
                spacing_size:
                    MS: 0.707
                    NS: 1
                    DS: 2
        
    dys:
        dir: dys_study
        groups:
            1: dyslexic
            2: control
        subjects:
            control: [foju, neda, buka, vikr, hoag, beni, jaga, kori,
                        tita, keli, bama, doan, szida, csda, kocev, adre,
                        urma, fope, mofr, koev, homa, plda, nemi, tado]
                      
            dyslexic: [pebe, vano, move, kodo, cski, buzs, luro, opcs,
                        boda, mava, foti, lurov, mead, foja, rupa, komo,
                        kani, duda, sako, elki, dobe, hlvi, road, hoor]
        experiments:
            et:
                features_path: '/data/dys_study/ET_features/AllSubjects48_TextLinesWithLeftValidation_correctionType1_limitedToReading_AllLines/AllSubsAllMeasuresOnOneSheetCondsOnSepSheets.xlsx'
                conditions: [SP1, SP2, SP3, SP4, SP5]
                spacing_size:
                    SP1: 0.707
                    SP2: 1
                    SP3: 1.3
                    SP4: 1.6
                    SP5: 1.9
                perf_data_path: '/data/dys_study/perf_data.csv'
                word_info_path: '/data/dys_study/word_info/word_info_all.csv'
            3dmh:
                data_path: '/data/dys_study/3DMH/3dmh_data.csv'
            wais:
                data_path: '/data/dys_study/WAIS/WAIS_data.csv'
            vsp:
                ecc_data_path: '/data/dys_study/VSP/vsp_ecc_data.csv'
                est_data_path: '/data/dys_study/VSP/vsp_est_data.csv'
                sum_data_path: '/data/dys_study/VSP/vsp_sum_data.csv'
                spacing_size:
                    SP1: 0.707
                    SP2: 1
                    SP3: 1.3

    dys_contr_2:
        dir: dys_contr_2_study
        groups:
            1: control
        subjects:
            control: ['009833', '044846', '321319', '643438', '862169', '269257',
                        '842608', '059694', '515155', '133288', '930517', '394107', 
                        '667207', '414822', '331536', '048298', '135230', '424174',
                        '319897', '927179', '612370', '213103', '284297', '103183',
                        '528213', '320268', '163753', '356349', '366394', '217720',
                        '390744', '050120', '205515', '822816', '303786', '638838',
                        '093925', '587631']
        experiments:
            et:
                features_path: '/data/dys_contr_2_study/ET_features/et_stats_subj_num_38/AllSubsAllMeasuresOnOneSheetCondsOnSepSheets.xlsx'
                conditions: [SP2]
                spacing_size:
                    SP2: 1
                perf_data_path: '/data/dys_contr_2_study/perf_data.csv'
                word_info_path: '/data/dys_contr_2_study/word_info/word_info_all.csv'
            3dmh:
                data_path: '/data/dys_contr_2_study/3dmh/3dmh_data.csv'
                info_path: '/data/dys_contr_2_study/3dmh/3dmh_subj_codes.csv'
                
params:
    et:
        # All measures
        meas_list_all:
            - Tot_sweep
            - Med_rspeed_wnum
            - Med_rspeed_chnum
            - Med_rspeed_mspan
            - Med_rspeed_tsweep
            - Totnum_sacc
            - Totnum_fsacc
            - Totnum_bsacc
            - Perc_fsacc
            - Perc_bsacc
            - Totnum_gliss
            - Totnum_fgliss
            - Totnum_bgliss
            - Perc_fgliss
            - Perc_bgliss
            - Perc_sacc_gliss
            - Perc_fsacc_gliss
            - Perc_bsacc_gliss
            - Perc_fsacc_fgliss
            - Perc_fsacc_bgliss
            - Perc_bsacc_fgliss
            - Perc_bsacc_bgliss
            - Totnum_lvel_gliss
            - Totnum_hvel_gliss
            - Perc_lvel_gliss
            - Perc_hvel_gliss
            - Perc_lvel_fgliss
            - Perc_lvel_bgliss
            - Perc_hvel_fgliss
            - Perc_hvel_bgliss
            - Totnum_gwcpeak
            - Totnum_gscpeak
            - Totnum_lvel_gwcpeak
            - Totnum_hvel_gwcpeak
            - Totnum_hvel_gwcpeakcorr
            - Totnum_hvel_gscpeak
            - Perc_gamp_critis
            - Perc_gdur_critis
            - Freq_fsacc
            - Freq_bsacc
            - Mean_meanfixvel
            - Mean_stdevfixvel
            - Med_saccpdetth
            - Med_saccdur
            - Med_fsaccdur
            - Med_bsaccdur
            - Med_saccamp
            - Med_fsaccamp
            - Med_bsaccamp
            - Med_saccpvel
            - Med_fsaccpvel
            - Med_bsaccpvel
            - Med_saccpacc
            - Med_fsaccpacc
            - Med_bsaccpacc
            - Med_glissdur
            - Med_fglissdur
            - Med_bglissdur
            - Med_lvglissdur
            - Med_hvglissdur
            - Med_glissamp
            - Med_fglissamp
            - Med_bglissamp
            - Med_lvglissamp
            - Med_hvglissamp
            - Med_glisspvel
            - Med_fglisspvel
            - Med_bglisspvel
            - Med_lvglisspvel
            - Med_hvglisspvel
            - Med_fixdur
            - Med_fXpos
            - Med_fYpos
            - Med_tsnum_maxvisspan
            - Med_fsnum_maxvisspan
            - Med_bsnum_maxvisspan
            - Med_tsnum_wnum
            - Med_fsnum_wnum
            - Med_bsnum_wnum
            - Med_tsnum_chnum
            - Med_fsnum_chnum
            - Med_bsnum_chnum
        
        # Measures selected for analyses
        meas_list:
            - Med_rspeed_wnum
            - Med_fixdur
            - Med_saccamp
            - Perc_fsacc
            - Perc_sacc_gliss
            - Perc_fsacc_gliss
            - Perc_bsacc_gliss
            - Perc_fsacc_fgliss
            - Perc_bsacc_fgliss
            - Med_fsaccamp
            - Med_bsaccamp
            - Perc_fgliss
            - Freq_fsacc
            - Freq_bsacc
            - Mean_meanfixvel
            - Mean_stdevfixvel
            - Med_saccpdetth
            - Med_saccdur
            - Med_fsaccdur
            - Med_bsaccdur
            - Med_glissdur
            - Med_fglissdur
            - Med_bglissdur
            - Med_glissamp
            - Med_fglissamp
            - Med_bglissamp
            - Med_tsnum_wnum
            - Med_fsnum_wnum
            - Med_bsnum_wnum
            - Med_saccpvel
            - Perc_lvel_gliss
            - Med_glisspvel
            - Med_lvglisspvel
            - Med_hvglisspvel
            
        # Minimal (non-redundant) measure list
        meas_list_min:
            - Med_rspeed_wnum
            - Med_fixdur
            - Perc_fsacc
            - Perc_fsacc_gliss
            - Perc_bsacc_gliss
            - Perc_fsacc_fgliss
            - Perc_bsacc_fgliss
            - Med_fsaccamp
            - Med_bsaccamp
            - Freq_fsacc
            - Freq_bsacc
            - Med_saccpdetth
            - Med_fsaccdur
            - Med_bsaccdur
            - Med_fglissdur
            - Med_bglissdur
            - Med_fglissamp
            - Med_bglissamp
            - Med_fsnum_wnum
            - Med_bsnum_wnum
            - Med_saccpvel
            - Perc_lvel_gliss
            - Med_lvglisspvel
            - Med_hvglisspvel
            
        # Minimal (non-redundant) measure list with the strongest predictors removed
        meas_list_min_2:
            - Med_rspeed_wnum
            - Med_fixdur
            - Perc_fsacc
            - Perc_fsacc_gliss
            - Perc_bsacc_gliss
            - Perc_fsacc_fgliss
            - Perc_bsacc_fgliss
            - Med_fsaccamp
            - Med_bsaccamp
            - Med_saccpdetth
            - Med_fsaccdur
            - Med_bsaccdur
            - Med_fglissdur
            - Med_bglissdur
            - Med_fglissamp
            - Med_bglissamp
            - Med_saccpvel
            - Perc_lvel_gliss
            - Med_lvglisspvel
            - Med_hvglisspvel
        
        word_info_list:
            - fix_num
            - first_fix_dur
            - total_reading_time
            - first_pass_reading_time
            - second_pass_reading_time
            - regr_path_reading_time
            - re_reading_time
            - regr_sacc_num

    3dmh:
        meas_list:
            Ny:
                - Ny_OlvAlszo_F
                - Ny_OlvAlszo_P
                - Ny_OlvAlszo_IRT
                - Ny_FonTorles_P
                - Ny_FonTorles_S
                - Ny_RAN_betu_S
                - Ny_RAN_szam_S
                - Ny_RAN_kep_S
                - Ny_SzotagTerj
                - Ny_Corsi
                - Ny_ReakcIdo_P
                - Ny_ReakcIdo_S
                - Ny_OlvGyak_F
                - Ny_OlvGyak_P
                - Ny_OlvRitka_F
                - Ny_OlvRitka_P
            St:     
                - St_OlvAlszo_F
                - St_OlvAlszo_P
                - St_FonTorles_P
                - St_FonTorles_S
                - St_RAN_betu_S
                - St_RAN_szam_S
                - St_RAN_kep_S
                - St_SzotagTerj
                - St_Corsi
                - St_ReakcIdo_S
                - St_FonTud_Sk
                - St_RAN_Sk
                - St_NyelvEml_Sk
                - St_TervizEml_Sk
                - St_OlvGyak_F
                - St_OlvRitka_F
                - St_Olvasas_Sk
            Perc:
                - Perc_OlvAlszo_F
                - Perc_OlvAlszo_P
                - Perc_FonTorles_P
                - Perc_FonTorles_S
                - Perc_RAN_betu
                - Perc_RAN_szam
                - Perc_RAN_kep
                - Perc_SzotagTerj
                - Perc_Corsi
                - Perc_ReakcIdo
                - Perc_FonTud_Sk
                - Perc_RAN_Sk
                - Perc_NyelvEml_Sk
                - Perc_TervizEml_Sk
                - Perc_OlvGyak_F
                - Perc_OlvRitka_F
                - Perc_Olvasas_Sk
    wais:
        meas_list:
            - iq_verbal_proc
            - iq_perceptual_proc
            - iq_working_mem
            - iq_proc_speed
            - iq_complet_test
    vsp:
        meas_list:
            - A
            - sigma1
            - sigma2
            - left_sum
            - middle_sum
            - right_sum
            - all_sum
            
        meas_list_all:
            - A
            - sigma1
            - sigma2
            - left_sum
            - middle_sum
            - right_sum
            - all_sum

